#!/bin/bash

# install.sh - Hindsight Installation Script
# Sets up the Hindsight activity tracking system

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║              Hindsight Installation Script                 ║"
echo "║      AI-powered activity tracking for macOS                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ─────────────────────────────────────────────────────────────────
# Prerequisites Check
# ─────────────────────────────────────────────────────────────────

echo -e "${BLUE}Checking prerequisites...${NC}"
echo ""

# Check macOS
echo -n "  macOS: "
if [[ "$(uname)" != "Darwin" ]]; then
    echo -e "${RED}FAILED${NC}"
    echo "  Error: Hindsight requires macOS (for screencapture)"
    exit 1
fi
echo -e "${GREEN}OK${NC} ($(sw_vers -productVersion))"

# Check Node.js
echo -n "  Node.js: "
if ! command -v node &> /dev/null; then
    echo -e "${RED}NOT FOUND${NC}"
    echo "  Node.js is required. Install from https://nodejs.org/"
    exit 1
fi
echo -e "${GREEN}OK${NC} ($(node -v))"

# Check Python 3 (for better-sqlite3 native build)
echo -n "  Python 3: "
if ! command -v python3 &> /dev/null; then
    echo -e "${YELLOW}WARNING${NC}"
    echo "  Python 3 is recommended for building native modules."
    echo "  Installation will proceed, but may fail if building better-sqlite3."
else
    echo -e "${GREEN}OK${NC} ($(python3 --version | cut -d' ' -f2))"
fi

# Check Xcode Command Line Tools
echo -n "  Xcode CLT: "
if ! xcode-select -p &> /dev/null; then
    echo -e "${YELLOW}NOT FOUND${NC}"
    echo ""
    echo "  Xcode Command Line Tools are required for native module compilation."
    read -p "  Install Xcode Command Line Tools? [Y/n] " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo "  Please install Xcode CLT manually: xcode-select --install"
        exit 1
    fi

    xcode-select --install
    echo "  Please complete the installation dialog and re-run this script."
    exit 0
fi
echo -e "${GREEN}OK${NC}"

echo ""
echo -e "${GREEN}All prerequisites satisfied!${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────
# lmstudio-js SDK Setup
# ─────────────────────────────────────────────────────────────────

echo -e "${BLUE}Setting up lmstudio-js SDK...${NC}"
echo ""

# Remove existing directory if present
if [[ -d "lmstudio-js" ]]; then
    echo "  Removing existing lmstudio-js directory..."
    rm -rf lmstudio-js
fi

echo "  Cloning lmstudio-js from GitHub..."
git clone https://github.com/lmstudio-ai/lmstudio-js.git --recursive

echo "  Installing lmstudio-js dependencies..."
(cd lmstudio-js && npm install)

echo "  Building lmstudio-js SDK..."
(cd lmstudio-js && npm run build)

# Verify SDK was built
if [[ ! -d "lmstudio-js/publish/sdk" ]]; then
    echo -e "${RED}Error: lmstudio-js SDK build failed (publish/sdk not found)${NC}"
    exit 1
fi

echo -e "  ${GREEN}lmstudio-js SDK ready${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────

# Check if .env already exists
if [[ -f "$SCRIPT_DIR/.env" ]]; then
    echo -e "${GREEN}Found existing .env file, skipping configuration...${NC}"
    echo ""
else
    echo -e "${BLUE}Configuration${NC}"
    echo ""

    # Get LM Studio API token
    echo "Get your API token from LM Studio > Settings > Developer"
    read -p "Enter LM Studio API token: " LM_API_TOKEN

    if [[ -z "$LM_API_TOKEN" ]]; then
        echo -e "${YELLOW}Warning: No API token provided. You can add it to .env later.${NC}"
        LM_API_TOKEN="your-token-here"
    fi
    echo ""

    # Get capture interval
    read -p "Screenshot capture interval in minutes [5]: " CAPTURE_INTERVAL
    CAPTURE_INTERVAL="${CAPTURE_INTERVAL:-5}"

    # Validate it's a number
    if ! [[ "$CAPTURE_INTERVAL" =~ ^[0-9]+\.?[0-9]*$ ]]; then
        echo -e "${RED}Error: Capture interval must be a number${NC}"
        exit 1
    fi
    echo ""

    # Get API port
    read -p "API server port [3000]: " PORT
    PORT="${PORT:-3000}"
    echo ""

    # Get vision model
    read -p "Vision model [qwen/qwen3-vl-4b]: " VISION_MODEL
    VISION_MODEL="${VISION_MODEL:-qwen/qwen3-vl-4b}"
    echo ""

    # Get web app port
    read -p "Web dashboard port [5173]: " WEB_PORT
    WEB_PORT="${WEB_PORT:-5173}"
    echo ""

    # Create .env file
    echo "  Creating .env file..."
    cat > .env << EOF
# Hindsight Configuration
# Generated by install.sh on $(date)

# LM Studio API token
LM_API_TOKEN=$LM_API_TOKEN

# API server port
PORT=$PORT

# Screenshot capture interval in minutes
CAPTURE_INTERVAL=$CAPTURE_INTERVAL

# Vision model for screenshot summarization
VISION_MODEL=$VISION_MODEL

# Web dashboard port
WEB_PORT=$WEB_PORT
EOF
fi

# ─────────────────────────────────────────────────────────────────
# Installation
# ─────────────────────────────────────────────────────────────────

echo -e "${BLUE}Installing Hindsight...${NC}"
echo ""

# Create data and logs directories
echo "  Creating data directories..."
mkdir -p data/screenshots
mkdir -p logs

# Install npm dependencies (--engine-strict enforces Node.js version from package.json)
echo "  Installing npm dependencies (this may take a moment)..."
npm install --engine-strict

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Installation Complete!                        ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Make sure LM Studio is running with the vision model loaded:"
echo "     Model: $VISION_MODEL"
echo ""
echo "  2. Start Hindsight:"
echo "     ./hindsight.sh start"
echo ""
echo "  3. Check status:"
echo "     ./hindsight.sh status"
echo ""
echo "  4. View logs:"
echo "     ./hindsight.sh logs"
echo ""
echo "  5. Open the web dashboard:"
echo "     http://localhost:$WEB_PORT"
echo ""
echo "  6. Stop Hindsight:"
echo "     ./hindsight.sh stop"
echo ""
echo "Configuration saved to: .env"
echo "Edit this file to change settings."
echo ""
